/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_JOYSTICKREADINGS_PB_H_INCLUDED
#define PB_JOYSTICKREADINGS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _JoystickReadings {
    int32_t channel1Reading;
    int32_t channel2Reading;
    int32_t channel3Reading;
    int32_t channel4Reading;
/* @@protoc_insertion_point(struct:JoystickReadings) */
} JoystickReadings;

/* Default values for struct fields */

/* Initializer values for message structs */
#define JoystickReadings_init_default            {0, 0, 0, 0}
#define JoystickReadings_init_zero               {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define JoystickReadings_channel1Reading_tag     1
#define JoystickReadings_channel2Reading_tag     2
#define JoystickReadings_channel3Reading_tag     3
#define JoystickReadings_channel4Reading_tag     4

/* Struct field encoding specification for nanopb */
extern const pb_field_t JoystickReadings_fields[5];

/* Maximum encoded size of messages (where known) */
#define JoystickReadings_size                    24

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define JOYSTICKREADINGS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
