/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "JoystickReadings.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t JoystickReadings_fields[5] = {
    PB_FIELD(  1, SINT32  , REQUIRED, STATIC  , FIRST, JoystickReadings, channel1Reading, channel1Reading, 0),
    PB_FIELD(  2, SINT32  , REQUIRED, STATIC  , OTHER, JoystickReadings, channel2Reading, channel1Reading, 0),
    PB_FIELD(  3, SINT32  , REQUIRED, STATIC  , OTHER, JoystickReadings, channel3Reading, channel2Reading, 0),
    PB_FIELD(  4, SINT32  , REQUIRED, STATIC  , OTHER, JoystickReadings, channel4Reading, channel3Reading, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
