/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "motorsinterface.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MotorsInterfaceMessage_fields[5] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, MotorsInterfaceMessage, motor1DC, motor1DC, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, MotorsInterfaceMessage, motor2Dc, motor1DC, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, MotorsInterfaceMessage, motor3DC, motor2Dc, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, MotorsInterfaceMessage, motor4DC, motor3DC, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
