/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "mpu6500.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MPU6500Readings_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, MPU6500Readings, accelerometer, accelerometer, &Vector3_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, MPU6500Readings, gyroscope, accelerometer, &Vector3_fields),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, MPU6500Readings, temperature, gyroscope, 0),
    PB_FIELD(  4, UINT64  , REQUIRED, STATIC  , OTHER, MPU6500Readings, timestamp, temperature, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MPU6500Readings, accelerometer) < 65536 && pb_membersize(MPU6500Readings, gyroscope) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MPU6500Readings)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MPU6500Readings, accelerometer) < 256 && pb_membersize(MPU6500Readings, gyroscope) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MPU6500Readings)
#endif


/* @@protoc_insertion_point(eof) */
