/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "vector3.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Vector3_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Vector3, x, x, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Vector3, y, x, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Vector3, z, y, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
